"""phase2 updated

Revision ID: 4a24961900c5
Revises: 9e1652788f84
Create Date: 2026-06-03 17:58:30.890178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a24961900c5'
down_revision: Union[str, None] = '9e1652788f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_contractors',
    sa.Column('pc_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('contractor_org_id', sa.BigInteger(), nullable=False),
    sa.Column('tower_id', sa.BigInteger(), nullable=True),
    sa.Column('scope', sa.String(length=100), nullable=True),
    sa.Column('assigned_by', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['contractor_org_id'], ['auth.organisations.org_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['master.projects.project_id'], ),
    sa.ForeignKeyConstraint(['tower_id'], ['master.towers.tower_id'], ),
    sa.PrimaryKeyConstraint('pc_id'),
    schema='master'
    )
    op.create_index('idx_pc_contractor', 'project_contractors', ['contractor_org_id'], unique=False, schema='master')
    op.create_index('idx_pc_project', 'project_contractors', ['project_id'], unique=False, schema='master')
    op.add_column('organisations', sa.Column('registered_by_org_id', sa.BigInteger(), nullable=True), schema='auth')
    op.create_foreign_key(None, 'organisations', 'organisations', ['registered_by_org_id'], ['org_id'], source_schema='auth', referent_schema='auth')
    op.add_column('project_team', sa.Column('contractor_org_id', sa.BigInteger(), nullable=False), schema='auth')
    op.create_foreign_key(None, 'project_team', 'organisations', ['contractor_org_id'], ['org_id'], source_schema='auth', referent_schema='auth')
    op.drop_constraint('projects_contractor_org_id_fkey', 'projects', schema='master', type_='foreignkey')
    op.drop_column('projects', 'contractor_org_id', schema='master')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('contractor_org_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='master')
    op.create_foreign_key('projects_contractor_org_id_fkey', 'projects', 'organisations', ['contractor_org_id'], ['org_id'], source_schema='master', referent_schema='auth')
    op.drop_constraint(None, 'project_team', schema='auth', type_='foreignkey')
    op.drop_column('project_team', 'contractor_org_id', schema='auth')
    op.drop_constraint(None, 'organisations', schema='auth', type_='foreignkey')
    op.drop_column('organisations', 'registered_by_org_id', schema='auth')
    op.drop_index('idx_pc_project', table_name='project_contractors', schema='master')
    op.drop_index('idx_pc_contractor', table_name='project_contractors', schema='master')
    op.drop_table('project_contractors', schema='master')
    # ### end Alembic commands ###
