"""add token blacklist

Revision ID: 8bceda843556
Revises: 976bff8d28a5
Create Date: 2026-06-04 12:53:45.576762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bceda843556'
down_revision: Union[str, None] = '976bff8d28a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blacklist', schema='auth')
    # ### end Alembic commands ###
