"""phase2 complete schema

Revision ID: 9e1652788f84
Revises: 
Create Date: 2026-06-03 16:48:46.359087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e1652788f84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('embedding_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('embedding_id'),
    schema='audit'
    )
    op.create_table('organisations',
    sa.Column('org_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('org_type', sa.Enum('CLIENT', 'CONTRACTOR', name='orgtype', schema='auth'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='orgstatus', schema='auth'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('org_id'),
    schema='auth'
    )
    op.create_table('components',
    sa.Column('component_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('component_type', sa.Enum('COLUMN', 'SLAB', 'BEAM', 'RAFT', 'SHEAR_WALL', 'STAIRCASE', 'LIFT_CORE', 'FOUNDATION', name='componenttype', schema='master'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('component_id'),
    schema='master'
    )
    op.create_table('grades',
    sa.Column('grade_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grade_name', sa.String(length=30), nullable=False),
    sa.Column('grade_type', sa.Enum('NORMAL', 'FREE_FLOW', name='gradetype', schema='master'), nullable=False),
    sa.Column('min_strength_mpa', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grade_variant', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('grade_id'),
    sa.UniqueConstraint('grade_name', name='uq_grade_name'),
    schema='master'
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('CLIENT_ADMIN', 'PROJECT_MANAGER', 'QUALITY_ENGINEER', 'SUPERVISOR', name='userrole', schema='auth'), nullable=False),
    sa.Column('is_org_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['auth.organisations.org_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('grade_thresholds',
    sa.Column('threshold_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grade_id', sa.BigInteger(), nullable=False),
    sa.Column('test_age_days', sa.Integer(), nullable=False),
    sa.Column('min_strength_mpa', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_code', sa.Enum('IS_456', 'IS_516', name='iscode', schema='master'), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['master.grades.grade_id'], ),
    sa.PrimaryKeyConstraint('threshold_id'),
    sa.UniqueConstraint('grade_id', 'test_age_days', name='uq_threshold_grade_age'),
    schema='master'
    )
    op.create_table('projects',
    sa.Column('project_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('contractor_org_id', sa.BigInteger(), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=True),
    sa.Column('project_location', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ON_HOLD', name='projectstatus', schema='master'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('plot_area_acres', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('builtup_area_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('saleable_area_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('no_of_towers', sa.Integer(), nullable=True),
    sa.Column('no_of_flats', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_org_id'], ['auth.organisations.org_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['auth.organisations.org_id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    schema='master'
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contractor_org_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('plant_location', sa.String(length=300), nullable=True),
    sa.Column('plant_distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_org_id'], ['auth.organisations.org_id'], ),
    sa.PrimaryKeyConstraint('supplier_id'),
    schema='master'
    )
    op.create_table('testing_labs',
    sa.Column('lab_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contractor_org_id', sa.BigInteger(), nullable=False),
    sa.Column('lab_name', sa.String(length=200), nullable=False),
    sa.Column('lab_type', sa.Enum('IN_HOUSE', 'THIRD_PARTY', name='labtype', schema='master'), nullable=False),
    sa.Column('accreditation_no', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_org_id'], ['auth.organisations.org_id'], ),
    sa.PrimaryKeyConstraint('lab_id'),
    schema='master'
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='auditaction', schema='audit'), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=50), nullable=False),
    sa.Column('old_values_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id'),
    schema='audit'
    )
    op.create_table('ingestion_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('document_type', sa.Enum('MIX_DESIGN', 'RMC_DETAIL', 'POUR_RECORD', 'GRADE_DETAIL', 'CUBE_TEST_REGISTER', name='documenttype', schema='audit'), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('error_detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id'),
    schema='audit'
    )
    op.create_table('org_invitations',
    sa.Column('invitation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CLIENT_ADMIN', 'PROJECT_MANAGER', 'QUALITY_ENGINEER', 'SUPERVISOR', name='userrole', schema='auth'), nullable=False),
    sa.Column('invited_by', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', name='invitationstatus', schema='auth'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['auth.organisations.org_id'], ),
    sa.PrimaryKeyConstraint('invitation_id'),
    sa.UniqueConstraint('token'),
    schema='auth'
    )
    op.create_table('project_team',
    sa.Column('team_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('PROJECT_MANAGER', 'QUALITY_ENGINEER', 'SUPERVISOR', name='teamrole', schema='auth'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['master.projects.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('team_id'),
    schema='auth'
    )
    op.create_table('mix_designs',
    sa.Column('mix_design_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_original_name', sa.String(length=300), nullable=True),
    sa.Column('contractor_name', sa.String(length=200), nullable=True),
    sa.Column('cement_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('flyash_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('water_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fine_agg_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fine_agg_2_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('coarse_20mm_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('coarse_10mm_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('admixture_kg', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('admixture_brand', sa.String(length=100), nullable=True),
    sa.Column('admixture_product', sa.String(length=100), nullable=True),
    sa.Column('admixture_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('wc_ratio', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('cement_type', sa.Enum('OPC_43', 'OPC_53', name='cementtype', schema='master'), nullable=True),
    sa.Column('coarse_agg_source', sa.String(length=100), nullable=True),
    sa.Column('fine_agg_source', sa.String(length=100), nullable=True),
    sa.Column('fine_agg_2_source', sa.String(length=100), nullable=True),
    sa.Column('flyash_source', sa.String(length=100), nullable=True),
    sa.Column('trial_mix_date', sa.Date(), nullable=True),
    sa.Column('strength_1day_mpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('strength_3day_mpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('strength_7day_mpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('strength_28day_mpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('approval_status', sa.Enum('APPROVED', 'REJECTED', 'IN_PROGRESS', name='mixapprovalstatus', schema='master'), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['master.grades.grade_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['master.projects.project_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['master.suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('mix_design_id'),
    schema='master'
    )
    op.create_index('idx_mix_supplier_grade_project', 'mix_designs', ['supplier_id', 'grade_id', 'project_id'], unique=False, schema='master')
    op.create_table('towers',
    sa.Column('tower_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('tower_name', sa.String(length=50), nullable=False),
    sa.Column('tower_code', sa.String(length=50), nullable=True),
    sa.Column('tower_description', sa.String(length=50), nullable=True),
    sa.Column('floors_total', sa.Integer(), nullable=True),
    sa.Column('no_of_flats', sa.Integer(), nullable=True),
    sa.Column('flats_per_floor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['master.projects.project_id'], ),
    sa.PrimaryKeyConstraint('tower_id'),
    sa.UniqueConstraint('project_id', 'tower_name', name='uq_tower_project_name'),
    schema='master'
    )
    op.create_table('rmc_dispatches',
    sa.Column('dispatch_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_id', sa.BigInteger(), nullable=False),
    sa.Column('volume_ordered_cum', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dispatch_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['master.grades.grade_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['master.suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('dispatch_id'),
    schema='transaction'
    )
    op.create_index('idx_rmc_supplier_date', 'rmc_dispatches', ['supplier_id', 'dispatch_time'], unique=False, schema='transaction')
    op.create_table('floors',
    sa.Column('floor_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tower_id', sa.BigInteger(), nullable=False),
    sa.Column('floor_label', sa.String(length=50), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tower_id'], ['master.towers.tower_id'], ),
    sa.PrimaryKeyConstraint('floor_id'),
    sa.UniqueConstraint('tower_id', 'floor_label', name='uq_floor_tower_label'),
    schema='master'
    )
    op.create_table('truck_dispatches',
    sa.Column('dispatch_token_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dispatch_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('supplier_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'ARRIVED', 'ACCEPTED', 'REJECTED', name='truckstatus', schema='transaction'), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('challan_number', sa.String(length=50), nullable=True),
    sa.Column('volume_cum', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wc_ratio_actual', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('slump_at_plant_mm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['transaction.rmc_dispatches.dispatch_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('dispatch_token_id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('token', name='uq_truck_token'),
    schema='transaction'
    )
    op.create_table('pours',
    sa.Column('pour_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('tower_id', sa.BigInteger(), nullable=False),
    sa.Column('floor_id', sa.BigInteger(), nullable=False),
    sa.Column('component_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_horizontal_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_vertical_id', sa.BigInteger(), nullable=True),
    sa.Column('mix_design_id', sa.BigInteger(), nullable=True),
    sa.Column('pour_date', sa.Date(), nullable=False),
    sa.Column('pour_reference', sa.String(length=30), nullable=True),
    sa.Column('volume_cum', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sub_contractor_name', sa.String(length=200), nullable=True),
    sa.Column('recorded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['master.components.component_id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['master.floors.floor_id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['master.grades.grade_id'], ),
    sa.ForeignKeyConstraint(['mix_design_id'], ['master.mix_designs.mix_design_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['master.projects.project_id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['supplier_horizontal_id'], ['master.suppliers.supplier_id'], ),
    sa.ForeignKeyConstraint(['supplier_vertical_id'], ['master.suppliers.supplier_id'], ),
    sa.ForeignKeyConstraint(['tower_id'], ['master.towers.tower_id'], ),
    sa.PrimaryKeyConstraint('pour_id'),
    schema='transaction'
    )
    op.create_index('idx_pours_pour_date', 'pours', ['pour_date'], unique=False, schema='transaction')
    op.create_index('idx_pours_project_tower_floor', 'pours', ['project_id', 'tower_id', 'floor_id'], unique=False, schema='transaction')
    op.create_table('cube_samples',
    sa.Column('sample_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pour_id', sa.BigInteger(), nullable=False),
    sa.Column('sample_reference', sa.String(length=50), nullable=True),
    sa.Column('cast_date', sa.Date(), nullable=False),
    sa.Column('cast_by', sa.BigInteger(), nullable=True),
    sa.Column('no_of_cubes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cast_by'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['pour_id'], ['transaction.pours.pour_id'], ),
    sa.PrimaryKeyConstraint('sample_id'),
    schema='transaction'
    )
    op.create_index('idx_cube_sample_pour', 'cube_samples', ['pour_id'], unique=False, schema='transaction')
    op.create_table('pour_dispatch_links',
    sa.Column('link_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pour_id', sa.BigInteger(), nullable=False),
    sa.Column('dispatch_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['transaction.rmc_dispatches.dispatch_id'], ),
    sa.ForeignKeyConstraint(['pour_id'], ['transaction.pours.pour_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    schema='transaction'
    )
    op.create_table('cube_tests',
    sa.Column('test_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.BigInteger(), nullable=False),
    sa.Column('lab_id', sa.BigInteger(), nullable=True),
    sa.Column('test_age_days', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('observed_strength_mpa', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('required_strength_mpa', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('result_status', sa.Enum('PENDING', 'PASS', 'FAIL', 'CRITICAL_FAILURE', name='resultstatus', schema='quality'), nullable=False),
    sa.Column('tested_by', sa.BigInteger(), nullable=True),
    sa.Column('lab_report_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['master.testing_labs.lab_id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['transaction.cube_samples.sample_id'], ),
    sa.ForeignKeyConstraint(['tested_by'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('test_id'),
    schema='quality'
    )
    op.create_index('idx_cube_test_date', 'cube_tests', ['test_date'], unique=False, schema='quality')
    op.create_index('idx_cube_test_sample', 'cube_tests', ['sample_id'], unique=False, schema='quality')
    op.create_index('idx_cube_test_status', 'cube_tests', ['result_status'], unique=False, schema='quality')
    op.create_table('ncrs',
    sa.Column('ncr_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('pour_id', sa.BigInteger(), nullable=False),
    sa.Column('ncr_number', sa.String(length=50), nullable=True),
    sa.Column('raised_by', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'CLOSED', name='ncrstatus', schema='quality'), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pour_id'], ['transaction.pours.pour_id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['quality.cube_tests.test_id'], ),
    sa.PrimaryKeyConstraint('ncr_id'),
    schema='quality'
    )
    op.create_index('idx_ncr_pour', 'ncrs', ['pour_id'], unique=False, schema='quality')
    op.create_index('idx_ncr_status', 'ncrs', ['status'], unique=False, schema='quality')
    op.create_table('ai_suggestions',
    sa.Column('suggestion_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ncr_id', sa.BigInteger(), nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('root_cause_text', sa.Text(), nullable=True),
    sa.Column('corrective_actions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_chunks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel', schema='quality'), nullable=True),
    sa.Column('ndt_recommended', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ncr_id'], ['quality.ncrs.ncr_id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['quality.cube_tests.test_id'], ),
    sa.PrimaryKeyConstraint('suggestion_id'),
    schema='quality'
    )
    op.create_table('corrective_actions',
    sa.Column('action_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ncr_id', sa.BigInteger(), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='actionstatus', schema='quality'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['ncr_id'], ['quality.ncrs.ncr_id'], ),
    sa.PrimaryKeyConstraint('action_id'),
    schema='quality'
    )
    op.create_table('penalties',
    sa.Column('penalty_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ncr_id', sa.BigInteger(), nullable=False),
    sa.Column('penalty_type', sa.Enum('RATE_REDUCTION', 'REJECTION', 'DEMOLITION', name='penaltytype', schema='quality'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applied_by', sa.BigInteger(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['ncr_id'], ['quality.ncrs.ncr_id'], ),
    sa.PrimaryKeyConstraint('penalty_id'),
    schema='quality'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penalties', schema='quality')
    op.drop_table('corrective_actions', schema='quality')
    op.drop_table('ai_suggestions', schema='quality')
    op.drop_index('idx_ncr_status', table_name='ncrs', schema='quality')
    op.drop_index('idx_ncr_pour', table_name='ncrs', schema='quality')
    op.drop_table('ncrs', schema='quality')
    op.drop_index('idx_cube_test_status', table_name='cube_tests', schema='quality')
    op.drop_index('idx_cube_test_sample', table_name='cube_tests', schema='quality')
    op.drop_index('idx_cube_test_date', table_name='cube_tests', schema='quality')
    op.drop_table('cube_tests', schema='quality')
    op.drop_table('pour_dispatch_links', schema='transaction')
    op.drop_index('idx_cube_sample_pour', table_name='cube_samples', schema='transaction')
    op.drop_table('cube_samples', schema='transaction')
    op.drop_index('idx_pours_project_tower_floor', table_name='pours', schema='transaction')
    op.drop_index('idx_pours_pour_date', table_name='pours', schema='transaction')
    op.drop_table('pours', schema='transaction')
    op.drop_table('truck_dispatches', schema='transaction')
    op.drop_table('floors', schema='master')
    op.drop_index('idx_rmc_supplier_date', table_name='rmc_dispatches', schema='transaction')
    op.drop_table('rmc_dispatches', schema='transaction')
    op.drop_table('towers', schema='master')
    op.drop_index('idx_mix_supplier_grade_project', table_name='mix_designs', schema='master')
    op.drop_table('mix_designs', schema='master')
    op.drop_table('project_team', schema='auth')
    op.drop_table('org_invitations', schema='auth')
    op.drop_table('ingestion_logs', schema='audit')
    op.drop_table('audit_logs', schema='audit')
    op.drop_table('testing_labs', schema='master')
    op.drop_table('suppliers', schema='master')
    op.drop_table('projects', schema='master')
    op.drop_table('grade_thresholds', schema='master')
    op.drop_table('users', schema='auth')
    op.drop_table('grades', schema='master')
    op.drop_table('components', schema='master')
    op.drop_table('organisations', schema='auth')
    op.drop_table('embeddings', schema='audit')
    # ### end Alembic commands ###
